### ISSUE TITLE
Support for linux with FTDI232

### ISSUE THREAD

**Issue by abood91** [sundermann/bno055_uart_driver#1]
Hello @stsundermann , Great job writing this. 
I would like to ask if possible to modify the library so it supports Bno055 connected to FTDI232 (or similar) on linux. the changes should be small since they will use the Bno055 over USB or serial com port.

Thanks again for the library and for consideration  :)

**Comment by sundermann** [comment]
I don't quite understand your question. This node is compatible with any serial to usb bridge connected to an bno055 via uart. I've been running the sensor with both an ftdi232 and pl2303 usb to serial converter successfully.

**Comment by abood91** [comment]
The idea is to use this code on a generic linux ?
To my understanding this use Ros ?

**Comment by sundermann** [comment]
This is meant to be used from linux. That's why I do not get the point of the question

**Comment by abood91** [comment]
Ok let me refine my question. could this be used without ros.h ?

**Comment by sundermann** [comment]
It could, but the point of this project was to integrate the bno055 into ROS. It should be quite easy to remove the ROS bits though.

**Comment by abood91** [comment]
Indeed, thus the suggestion :). this should be marked as feature request not an issue

**Comment by sundermann** [comment]
I'm not going to remove the ROS dependency on this because this has been written to be used with ROS in the first place. Feel free to fork this repository and work on it though.

**Comment by abood91** [comment]
Thanks for the effort :)
